services:
  db:
    image: postgres
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  web:
    build: .
    container_name: dogs
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python dog_manager/manage.py migrate && python dog_manager/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pgdata: