# Generated by Django 5.1.7 on 2025-04-01 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="breed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dogs",
                to="pets.breed",
            ),
        ),
    ]
